"""structure reviewed

Revision ID: ae4e4f705308
Revises: c8a9defcd207
Create Date: 2025-12-15 21:13:52.216677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4e4f705308'
down_revision: Union[str, Sequence[str], None] = 'c8a9defcd207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measure', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('person_plan_id_fkey'), 'person', type_='foreignkey')
    op.create_foreign_key(None, 'person', 'plan', ['plan_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_training_exercise', 'training_plan', ['training_id', 'exercise_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_training_exercise', 'training_plan', type_='unique')
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.create_foreign_key(op.f('person_plan_id_fkey'), 'person', 'plan', ['plan_id'], ['id'])
    op.alter_column('measure', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
