"""Ajustes nas fks

Revision ID: b9b015a132b3
Revises: 4dbee98369cf
Create Date: 2025-11-26 22:09:43.022339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b015a132b3'
down_revision: Union[str, Sequence[str], None] = '4dbee98369cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exercise_category_id_fkey'), 'exercise', type_='foreignkey')
    op.create_foreign_key(None, 'exercise', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('measure_person_id_fkey'), 'measure', type_='foreignkey')
    op.create_foreign_key(None, 'measure', 'person', ['person_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('student_person_id_fkey'), 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'person', ['person_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('teacher_person_id_fkey'), 'teacher', type_='foreignkey')
    op.create_foreign_key(None, 'teacher', 'person', ['person_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('training_person_id_fkey'), 'training', type_='foreignkey')
    op.create_foreign_key(None, 'training', 'person', ['person_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('training_plan_training_id_fkey'), 'training_plan', type_='foreignkey')
    op.drop_constraint(op.f('training_plan_exercise_id_fkey'), 'training_plan', type_='foreignkey')
    op.create_foreign_key(None, 'training_plan', 'exercise', ['exercise_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'training_plan', 'training', ['training_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_person_id_fkey'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'person', ['person_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('user_person_id_fkey'), 'user', 'person', ['person_id'], ['id'])
    op.drop_constraint(None, 'training_plan', type_='foreignkey')
    op.drop_constraint(None, 'training_plan', type_='foreignkey')
    op.create_foreign_key(op.f('training_plan_exercise_id_fkey'), 'training_plan', 'exercise', ['exercise_id'], ['id'])
    op.create_foreign_key(op.f('training_plan_training_id_fkey'), 'training_plan', 'training', ['training_id'], ['id'])
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.create_foreign_key(op.f('training_person_id_fkey'), 'training', 'person', ['person_id'], ['id'])
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_person_id_fkey'), 'teacher', 'person', ['person_id'], ['id'])
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key(op.f('student_person_id_fkey'), 'student', 'person', ['person_id'], ['id'])
    op.drop_constraint(None, 'measure', type_='foreignkey')
    op.create_foreign_key(op.f('measure_person_id_fkey'), 'measure', 'person', ['person_id'], ['id'])
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.create_foreign_key(op.f('exercise_category_id_fkey'), 'exercise', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
