"""measure structure update

Revision ID: c8a9defcd207
Revises: 782deb558abc
Create Date: 2025-12-15 16:19:51.738227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8a9defcd207'
down_revision: Union[str, Sequence[str], None] = '782deb558abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_measure',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('measure_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('measure', sa.Column('name', sa.String(), nullable=False))
    op.add_column('measure', sa.Column('unit', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'measure', ['name'])
    op.drop_constraint(op.f('measure_person_id_fkey'), 'measure', type_='foreignkey')
    op.drop_column('measure', 'measure_date')
    op.drop_column('measure', 'measure_type')
    op.drop_column('measure', 'value')
    op.drop_column('measure', 'person_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measure', sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('measure', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('measure', sa.Column('measure_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('measure', sa.Column('measure_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('measure_person_id_fkey'), 'measure', 'person', ['person_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'measure', type_='unique')
    op.drop_column('measure', 'unit')
    op.drop_column('measure', 'name')
    op.drop_table('person_measure')
    # ### end Alembic commands ###
